name: "Policy Pull"
description: "Pull policy image from registry"
author: "Aserto Inc."
branding:
  icon: skip-back
  color: blue
inputs:
  tag:
    description: "image tag to be pulled from registry"
    required: true
  verbosity:
    description: "verbosity level [info|error|debug|trace]"
    required: true
    default: error
runs:
  using: docker
  image: 'docker://ghcr.io/opcr-io/policy:0.1'
  entrypoint: /app/pull.sh
